/**
 * Autogenerated main file
 *
 *
 *  Created on: 
 *      Author: Ravel
 */

#include "models.h" //since we have same naming
#include "api/api_timer.h"
//here we only declare system subscribed event callbacks

//start with models
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void app_device_model__app_system_ctr__arrived(void *rctx);
//departed event
void app_device_model__app_system_ctr__departed(void *rctx);
//buffer is full event
void app_device_model__app_system_ctr__full(void *rctx);
//save done event
void app_device_model__app_system_ctr__saveDone(void *rctx);
//data saved to the buffer event
void app_device_model__app_system_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void boot_error_model__em_bootstrap_controller_ctr__arrived(void *rctx);
//departed event
void boot_error_model__em_bootstrap_controller_ctr__departed(void *rctx);
//buffer is full event
void boot_error_model__em_bootstrap_controller_ctr__full(void *rctx);
//save done event
void boot_error_model__em_bootstrap_controller_ctr__saveDone(void *rctx);
//data saved to the buffer event
void boot_error_model__em_bootstrap_controller_ctr__bufferSaveDone(void *rctx);

//generating source callbacks declarions

void em_bootstrap_controller_ctr__system_booted(void *rctx);

//**** end autogenerated file **//
 