/**
 * Autogenerated main file
 *
 *
 *  Created on: 
 *      Author: Ravel
 */

#include "models.h" //since we have same naming
#include "api/api_timer.h"
//here we only declare system subscribed event callbacks

//start with models
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void app_config_model__measurement_controller_ctr__arrived(void *rctx);
//departed event
void app_config_model__measurement_controller_ctr__departed(void *rctx);
//buffer is full event
void app_config_model__measurement_controller_ctr__full(void *rctx);
//save done event
void app_config_model__measurement_controller_ctr__saveDone(void *rctx);
//data saved to the buffer event
void app_config_model__measurement_controller_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void measurement_model__measurement_controller_ctr__arrived(void *rctx);
//departed event
void measurement_model__measurement_controller_ctr__departed(void *rctx);
//buffer is full event
void measurement_model__measurement_controller_ctr__full(void *rctx);
//save done event
void measurement_model__measurement_controller_ctr__saveDone(void *rctx);
//data saved to the buffer event
void measurement_model__measurement_controller_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void measurement_packet_model__measurement_controller_ctr__arrived(void *rctx);
//departed event
void measurement_packet_model__measurement_controller_ctr__departed(void *rctx);
//buffer is full event
void measurement_packet_model__measurement_controller_ctr__full(void *rctx);
//save done event
void measurement_packet_model__measurement_controller_ctr__saveDone(void *rctx);
//data saved to the buffer event
void measurement_packet_model__measurement_controller_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void encrypted_blob_model__measurement_controller_ctr__arrived(void *rctx);
//departed event
void encrypted_blob_model__measurement_controller_ctr__departed(void *rctx);
//buffer is full event
void encrypted_blob_model__measurement_controller_ctr__full(void *rctx);
//save done event
void encrypted_blob_model__measurement_controller_ctr__saveDone(void *rctx);
//data saved to the buffer event
void encrypted_blob_model__measurement_controller_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void a_d_c_model_model__measurement_controller_ctr__arrived(void *rctx);
//departed event
void a_d_c_model_model__measurement_controller_ctr__departed(void *rctx);
//buffer is full event
void a_d_c_model_model__measurement_controller_ctr__full(void *rctx);
//save done event
void a_d_c_model_model__measurement_controller_ctr__saveDone(void *rctx);
//data saved to the buffer event
void a_d_c_model_model__measurement_controller_ctr__bufferSaveDone(void *rctx);

//generating source callbacks declarions

void measurement_controller_ctr__system_booted(void *rctx);

//**** end autogenerated file **//
 