/**
 * Autogenerated main file
 *
 *
 *  Created on: 
 *      Author: Ravel
 */

#include "models.h" //since we have same naming
#include "api/api_timer.h"
//here we only declare system subscribed event callbacks

//start with models
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void update_frequency_model__randomizer_ctr__arrived(void *rctx);
//departed event
void update_frequency_model__randomizer_ctr__departed(void *rctx);
//buffer is full event
void update_frequency_model__randomizer_ctr__full(void *rctx);
//save done event
void update_frequency_model__randomizer_ctr__saveDone(void *rctx);
//data saved to the buffer event
void update_frequency_model__randomizer_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void random_model__randomizer_ctr__arrived(void *rctx);
//departed event
void random_model__randomizer_ctr__departed(void *rctx);
//buffer is full event
void random_model__randomizer_ctr__full(void *rctx);
//save done event
void random_model__randomizer_ctr__saveDone(void *rctx);
//data saved to the buffer event
void random_model__randomizer_ctr__bufferSaveDone(void *rctx);

//generating source callbacks declarions
 
void randomizer_ctr__timer__timer_periodic__expired(void * p_context);
 

 

void randomizer_ctr__system_booted(void *rctx);

//**** end autogenerated file **//
 