/**
 * Autogenerated main file
 *
 *
 *  Created on: 
 *      Author: Ravel
 */

#include "models.h" //since we have same naming
#include "api/api_timer.h"
//here we only declare system subscribed event callbacks

//start with models
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void frequency_model__random_controller_cloud_ctr__arrived(void *rctx);
//departed event
void frequency_model__random_controller_cloud_ctr__departed(void *rctx);
//buffer is full event
void frequency_model__random_controller_cloud_ctr__full(void *rctx);
//save done event
void frequency_model__random_controller_cloud_ctr__saveDone(void *rctx);
//data saved to the buffer event
void frequency_model__random_controller_cloud_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void random_model__random_controller_cloud_ctr__arrived(void *rctx);
//departed event
void random_model__random_controller_cloud_ctr__departed(void *rctx);
//buffer is full event
void random_model__random_controller_cloud_ctr__full(void *rctx);
//save done event
void random_model__random_controller_cloud_ctr__saveDone(void *rctx);
//data saved to the buffer event
void random_model__random_controller_cloud_ctr__bufferSaveDone(void *rctx);
//* record events defined for each controller */
//TODO: add many to many relation support
//arrived event
void boot_error_model__random_controller_embedded_ctr__arrived(void *rctx);
//departed event
void boot_error_model__random_controller_embedded_ctr__departed(void *rctx);
//buffer is full event
void boot_error_model__random_controller_embedded_ctr__full(void *rctx);
//save done event
void boot_error_model__random_controller_embedded_ctr__saveDone(void *rctx);
//data saved to the buffer event
void boot_error_model__random_controller_embedded_ctr__bufferSaveDone(void *rctx);

//generating source callbacks declarions

void random_controller_embedded_ctr__system_booted(void *rctx);

//**** end autogenerated file **//
 