/**
 * Autogenerated main file
 *
 *
 *  Created on: 13:14:31 10/12/2016
 *      Author: Ravel
 */
 #include "app_timer.h"
 #include "nrf_log.h"
 #include "nrf_log_ctrl.h"


 #include "ravel_layer.h"
 #include "api_timer.h"
 #include "../models.h"


/**
 * Random model dispatchers
 */
 bool random_model__channel_connected = false;
 void random_model__channel_enabled(){ random_model__channel_connected = true; }
 void random_model__channel_disabled() { random_model__channel_connected = false; }
 bool random_model__is_connected() { return random_model__channel_connected; }



 bool boot_error_model__channel_connected = false;
 void boot_error_model__channel_enabled(){ boot_error_model__channel_connected = true; }
 void boot_error_model__channel_disabled() { boot_error_model__channel_connected = false; }
 bool boot_error_model__is_connected() { return boot_error_model__channel_connected; }


/**
 * System dispatchers
 */

void system_api__device_connected(){
	NRF_LOG_INFO("Connected to a device \r\n");

}
void system_api__device_disconnected(){
	NRF_LOG_INFO("Disconnected from a device \r\n");
}

//deal with added data
void  random_model__data_added(){

}
//deal with added data
void  frequency_model__data_added(){

}
//deal with added data
void  boot_error_model__data_added(){

}
//** end autogenerated file **//
 