 /**
  * Autogenerated main file
  *
  *
  *  Created on: 13:14:31 10/12/2016
  *      Author: Ravel
    */
#ifndef API_RAVEL_LAYER_H_
#define API_RAVEL_LAYER_H_
#include <stdint.h>
#include <string.h>

#include "api_ble.h"


/**
 * System dispatchers
 */

void system_api__device_connected();
void system_api__device_disconnected();

void  random_model__data_added();
void  frequency_model__data_added();
void  boot_error_model__data_added();


//model channel connectivity dispatching
bool random_model__is_connected();
void random_model__channel_enabled();
void random_model__channel_disabled();



bool boot_error_model__is_connected();
void boot_error_model__channel_enabled();
void boot_error_model__channel_disabled();


//** end autogenerated files *//
#endif /* API_RAVEL_LAYER_H_ */