#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#define NRF_LOG_ENABLED 1
#define NRF_LOG_DEFAULT_LEVEL 4
#define NRF_LOG_USES_RTT 1
#define NRF_LOG_BACKEND_SERIAL_USES_RTT 1
#define NRF_LOG_BACKEND_SERIAL_USES_UART 0

#endif /* APP_CONFIG_H_ */