# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Originator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleModelMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived', models.DateTimeField(auto_now_add=True)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.Originator')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleModle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField(default=5)),
                ('idx', models.IntegerField()),
                ('field1', models.IntegerField()),
                ('field2', models.IntegerField()),
                ('field3', models.IntegerField()),
                ('field4', models.IntegerField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.SimpleModelMeta')),
            ],
        ),
    ]
