/**
 * Autogenerated main file
 *
 *
 *  Created on: 11:44:58 10/12/2016
 *      Author: Ravel
 */
 #include "app_timer.h"
 #include "nrf_log.h"
 #include "nrf_log_ctrl.h"


 #include "ravel_layer.h"
 #include "api_timer.h"
 #include "../models.h"


/**
 * Random model dispatchers
 */
 bool p_phase_model__channel_connected = false;
 void p_phase_model__channel_enabled(){ p_phase_model__channel_connected = true; }
 void p_phase_model__channel_disabled() { p_phase_model__channel_connected = false; }
 bool p_phase_model__is_connected() { return p_phase_model__channel_connected; }


 bool compressed_sample_model__channel_connected = false;
 void compressed_sample_model__channel_enabled(){ compressed_sample_model__channel_connected = true; }
 void compressed_sample_model__channel_disabled() { compressed_sample_model__channel_connected = false; }
 bool compressed_sample_model__is_connected() { return compressed_sample_model__channel_connected; }



/**
 * System dispatchers
 */

void system_api__device_connected(){
	NRF_LOG_INFO("Connected to a device \r\n");

}
void system_api__device_disconnected(){
	NRF_LOG_INFO("Disconnected from a device \r\n");
}

//deal with added data
void  vibration_model__data_added(){

}
//deal with added data
void  p_phase_model__data_added(){

}
//deal with added data
void  compressed_sample_model__data_added(){

}
//deal with added data
void  transmit_c_s_model__data_added(){

}
//** end autogenerated file **//
 