/**
 * Autogenerated main file
 *
 *
 *  Created on: 
 *      Author: Ravel
 */
#include "app_timer.h"
#include "nrf_log.h"
#include "nrf_log_ctrl.h"

#include "models.h"
#include "api_ble.h"
#include "coordinator_ctr.h"

//implement subscribed model events

 TransmitCSModel repModel; 

//translate actions for the subscribed events
//TODO: check if controller is bubscribed to the particular model event

//void random_model_ctr__set_config_model(ConfigModel *cm){
//TODO: fix controller inner body
	//memset(&localCm, 0, sizeof(ConfigModel));
	//localCm.time = cm->time;
	//localCm.frequency = cm->frequency;
//}


void p_phase_model__coordinator_ctr__arrived(void *rctx ){
    NRF_LOG_INFO("p_phase_model__coordinator_ctr__arrived\r\n");
	//if(((RavelContext)rctx)->error == NRF_SUCCESS){
		//}
    	//NRF_LOG_INFO("Arrived frequency: %d \r\n", localCm.frequency);
    	//config_model__sys_write_to_BLE(&m_ravel_service, &localCm);
}

void p_phase_model__coordinator_ctr__departed(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("p_phase_model__coordinator_ctr__departed\r\n");
}
void p_phase_model__coordinator_ctr__full(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("p_phase_model__coordinator_ctr__full\r\n");
}

void p_phase_model__coordinator_ctr__saveDone(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("p_phase_model__coordinator_ctr__arrived\r\n");
}
void p_phase_model__coordinator_ctr__bufferSaveDone(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("p_phase_model__coordinator_ctr__bufferSaveDone\r\n");
}


//translate actions for the subscribed events
//TODO: check if controller is bubscribed to the particular model event

//void random_model_ctr__set_config_model(ConfigModel *cm){
//TODO: fix controller inner body
	//memset(&localCm, 0, sizeof(ConfigModel));
	//localCm.time = cm->time;
	//localCm.frequency = cm->frequency;
//}


void compressed_sample_model__coordinator_ctr__arrived(void *rctx ){
    NRF_LOG_INFO("compressed_sample_model__coordinator_ctr__arrived\r\n");
	//if(((RavelContext)rctx)->error == NRF_SUCCESS){
		//}
    	//NRF_LOG_INFO("Arrived frequency: %d \r\n", localCm.frequency);
    	//config_model__sys_write_to_BLE(&m_ravel_service, &localCm);
}

void compressed_sample_model__coordinator_ctr__departed(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("compressed_sample_model__coordinator_ctr__departed\r\n");
}
void compressed_sample_model__coordinator_ctr__full(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("compressed_sample_model__coordinator_ctr__full\r\n");
}

void compressed_sample_model__coordinator_ctr__saveDone(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("compressed_sample_model__coordinator_ctr__arrived\r\n");
}
void compressed_sample_model__coordinator_ctr__bufferSaveDone(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("compressed_sample_model__coordinator_ctr__bufferSaveDone\r\n");
}


//translate actions for the subscribed events
//TODO: check if controller is bubscribed to the particular model event

//void random_model_ctr__set_config_model(ConfigModel *cm){
//TODO: fix controller inner body
	//memset(&localCm, 0, sizeof(ConfigModel));
	//localCm.time = cm->time;
	//localCm.frequency = cm->frequency;
//}


void transmit_c_s_model__coordinator_ctr__arrived(void *rctx ){
    NRF_LOG_INFO("transmit_c_s_model__coordinator_ctr__arrived\r\n");
	//if(((RavelContext)rctx)->error == NRF_SUCCESS){
		//}
    	//NRF_LOG_INFO("Arrived frequency: %d \r\n", localCm.frequency);
    	//config_model__sys_write_to_BLE(&m_ravel_service, &localCm);
}

void transmit_c_s_model__coordinator_ctr__departed(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("transmit_c_s_model__coordinator_ctr__departed\r\n");
}
void transmit_c_s_model__coordinator_ctr__full(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("transmit_c_s_model__coordinator_ctr__full\r\n");
}

void transmit_c_s_model__coordinator_ctr__saveDone(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("transmit_c_s_model__coordinator_ctr__arrived\r\n");
}
void transmit_c_s_model__coordinator_ctr__bufferSaveDone(void *rctx){
	//do things when model data arrives
	NRF_LOG_INFO("transmit_c_s_model__coordinator_ctr__bufferSaveDone\r\n");
}



//generating source callbacks implementations

void coordinator_ctr__system_booted(void *rctx){
	randomizer_ctr__timer__timer_periodic__start(1000);
}


//*** End auto generated file coordinator_ctr.c **//