/**
 * Autogenerated main file
 *
 *
 *  Created on: 13:07:23 10/12/2016
 *      Author: Ravel
 */
 #include "app_timer.h"
 #include "nrf_log.h"
 #include "nrf_log_ctrl.h"


 #include "ravel_layer.h"
 #include "api_timer.h"
 #include "../models.h"


/**
 * Random model dispatchers
 */
 bool boot_error_model__channel_connected = false;
 void boot_error_model__channel_enabled(){ boot_error_model__channel_connected = true; }
 void boot_error_model__channel_disabled() { boot_error_model__channel_connected = false; }
 bool boot_error_model__is_connected() { return boot_error_model__channel_connected; }





 bool measurement_packet_model__channel_connected = false;
 void measurement_packet_model__channel_enabled(){ measurement_packet_model__channel_connected = true; }
 void measurement_packet_model__channel_disabled() { measurement_packet_model__channel_connected = false; }
 bool measurement_packet_model__is_connected() { return measurement_packet_model__channel_connected; }



/**
 * System dispatchers
 */

void system_api__device_connected(){
	NRF_LOG_INFO("Connected to a device \r\n");

}
void system_api__device_disconnected(){
	NRF_LOG_INFO("Disconnected from a device \r\n");
}

//deal with added data
void  app_device_model__data_added(){

}
//deal with added data
void  app_config_model__data_added(){

}
//deal with added data
void  boot_error_model__data_added(){

}
//deal with added data
void  a_d_c_model_model__data_added(){

}
//deal with added data
void  device_location_model_model__data_added(){

}
//deal with added data
void  measurement_model__data_added(){

}
//deal with added data
void  measurement_packet_model__data_added(){

}
//deal with added data
void  encrypted_blob_model__data_added(){

}
//** end autogenerated file **//
 